In [10]:
import numpy as np

array = np.arange(0,12)

print(array)

print("subtract :",array -10)
print("multiply",array *10)
print("Divide",array /10)
print("Power",array **2)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
subtract : [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1]
multiply [  0  10  20  30  40  50  60  70  80  90 100 110]
Divide [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]
Power [  0   1   4   9  16  25  36  49  64  81 100 121]


In [14]:
import numpy as np

x =np.arange(20)
print(x)
print()

print(x.shape)
print()

print(x.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

(20,)

1


In [17]:

import numpy as np
arr= np.array([2,3,1,8,6,4,7,0,9,5])
print(arr)


[2 3 1 8 6 4 7 0 9 5]


In [28]:

import numpy as matlib
import numpy as np
a = np.array([[1,2],[2,1]])
b = np.array([[10,11],[12,16]])
np.dot(a,b)



array([[34, 43],
       [32, 38]])